version: "{build}"

platform:
- x64
- x86

environment:
  CIBW_TEST_COMMAND: python setup.py test
  matrix:
  - WITH_LUA: true
  - WITH_LUAJIT: true

matrix:
  fast_finish: true

install:
# Get all submodules, since AppVeyor doesn't clone with '--recursive':
- git submodule update --init --recursive # inside the repository directory
- pip install cibuildwheel==0.9.4
- echo PLATFORM=%PLATFORM%
- if "%PLATFORM%" EQU "x86" ( set CIBW_SKIP=*-win_amd64 )
- if "%PLATFORM%" EQU "X64" ( set CIBW_SKIP=*-win32 )
- echo CIBW_SKIP=%CIBW_SKIP%

before_build:
- if "%PLATFORM%" EQU "x64" ( set VS_ARCH=amd64 )
- call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %VS_ARCH%

- cd third-party/luajit/src
- if "%WITH_LUAJIT%" EQU "true" ( call msvcbuild.bat )
- cd ../../..

build_script:
- cibuildwheel --output-dir %APPVEYOR_BUILD_FOLDER%\wheelhouse

artifacts:
- path: "wheelhouse\\*.whl"
  name: Wheels

#deploy:
#  release: lupa-$(LUPA_VERSION)_luajit-$(LUAJIT_VERSION)_build-$(appveyor_build_version)
#  provider: GitHub
#  auth_token:
#    secure: Mg6hwOigPz3G3y//LToGND67Vbp1kKRJu6grZbiJAOlRGcN/jVIFI3ePKXJySYh+
#  on:
#    branch: master                 # release from master branch only
